In [1]:
import numpy as np

In [8]:
# append
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.append(a, [7, 8, 9])
c = np.append(a, [1, 0, 1, 0])
print(a.shape)
print(b.shape)
print(b)
print(c.shape)
print(c)

(2, 3)
(9,)
[1 2 3 4 5 6 7 8 9]
(10,)
[1 2 3 4 5 6 1 0 1 0]


In [25]:
# insert(array, obj, value, axis)
# obj: int, slice, or sequence of ints
# broadcast might occur
d = np.insert(a, 1, [7], axis=0)
print(d)
e = np.insert(a, 1, [7, 8, 9], axis=0)
print(e)
f = np.insert(a, 1, [[7], [8], [9]], axis=0)
print(f)
g = np.insert(a, 2, [7], axis=1)
print(g)
h = np.insert(a, 2, [7, 8], axis=1)
print(h)
i = np.insert(a, 2, [[7, 8], [9, 10]], axis=1)
print(i)

[[1 2 3]
 [7 7 7]
 [4 5 6]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[1 2 3]
 [7 7 7]
 [8 8 8]
 [9 9 9]
 [4 5 6]]
[[1 2 7 3]
 [4 5 7 6]]
[[1 2 7 3]
 [4 5 8 6]]
[[ 1  2  7  9  3]
 [ 4  5  8 10  6]]


In [26]:
# delete
j = np.delete(a, 1, axis=0)
print(j)
k = np.delete(a, 2, axis=1)
print(k)

[[1 2 3]]
[[1 2]
 [4 5]]
