In [1]:
import numpy as np

In [7]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [9]:
np.count_nonzero(x < 6)

8

In [10]:
np.sum(x < 6)

8

In [11]:
np.count_nonzero(x < 6, axis=1)   # count in each row

array([4, 2, 2], dtype=int64)

In [12]:
np.any(x > 8)   # any values greater than 8?

True

In [13]:
np.all(x < 10) # are all values less than 10?

True

In [14]:
np.all(x < 8, axis=1)

array([ True, False,  True])

In [15]:
# Masking operation
x[x < 5]    # find the values that are less than 5

array([0, 3, 3, 3, 2, 4])