In [1]:
import numpy as np

In [2]:
"""one dimension"""
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, b)

[10 20 30 40] [0 1 2 3]


In [8]:
a - b

array([10, 19, 28, 37])

In [7]:
a * b

array([  0,  20,  60, 120])

In [9]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [10]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [11]:
b < 2

array([ True,  True, False, False])

In [12]:
c = np.array([1, 1, 4, 3])
c == b

array([False,  True, False,  True])

In [17]:
"""multi dimension"""
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape((2, 2))
print(a,'\n')
print(b)

[[1 1]
 [0 1]] 

[[0 1]
 [2 3]]


In [18]:
a.dot(b)

array([[2, 4],
       [2, 3]])

In [19]:
np.dot(a, b)

array([[2, 4],
       [2, 3]])

In [27]:
np.random.seed(0)
a = np.random.random((2, 4))
print('a:', a, '\n')
print('min in array:', a.min())
print('min in each col', np.min(a, axis=0))
print('min in each row', np.min(a, axis=1), '\n')
print('sum of array:', a.sum())
print('sum by col', np.sum(a, axis=0))
print('sum by row', np.sum(a, axis=1))

a: [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]] 

min in array: 0.4236547993389047
min in each col [0.4236548  0.64589411 0.43758721 0.54488318]
min in each row [0.54488318 0.4236548 ] 

sum of array: 4.810558553818618
sum by col [0.9724683  1.36108348 1.04035059 1.43665618]
sum by row [2.41164943 2.39890912]


In [64]:
a = np.arange(2, 14).reshape((3, 4))
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [31]:
# index of min, max
np.argmin(a), np.argmax(a)

(0, 11)

In [34]:
# mean of the array
np.mean(a)
np.average(a)
a.mean()

7.5

In [35]:
# median
np.median(a)

7.5

In [36]:
# cummulate
np.cumsum(a)

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90], dtype=int32)

In [65]:
np.cumprod(a)

array([         2,          6,         24,        120,        720,
             5040,      40320,     362880,    3628800,   39916800,
        479001600, 1932053504], dtype=int32)

In [37]:
b = np.array([[3, 5, 9],
              [4, 8, 10]])
np.diff(b)

array([[2, 4],
       [4, 2]])

In [41]:
c = np.array([[0, 5, 9],
              [4, 0, 10]])
np.nonzero(c)
# returns 2 arrays with x of all nonzero elements, y of  all nonnzero elements

(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))

In [48]:
#  numpy.sort(a, axis=-1, kind=None, order=None)[source]
a = np.arange(14, 2, -1).reshape(3, 4)
np.sort(a) 
# only applies to each row (default axis -1, or last axis, in 2d: axis=1)

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

In [55]:
np.sort(a, axis=0) # sort in each coulmn

array([[ 6,  5,  4,  3],
       [10,  9,  8,  7],
       [14, 13, 12, 11]])

In [58]:
np.sort(a, axis=None) # sort the flatten array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
# structured array
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), 
          ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)       # create a structured array
print(a)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [61]:
# sort by height
np.sort(a, order='height')   

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [62]:
# sort by age, then bby height
np.sort(a, order=['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])