In [90]:
import numpy as np
import matplotlib as plt

np.random.seed(0)

values = np.random.randint(1,10,size=5)
values

array([6, 1, 4, 4, 8])

In [3]:
1/values

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [9]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
2 ** x # 2^x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [11]:
x ** x

array([[       1,        1,        4],
       [      27,      256,     3125],
       [   46656,   823543, 16777216]], dtype=int32)

In [14]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x +5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)   # floor division
print("- x =", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x %2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
- x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [19]:
print(np.add(x, 2))
print(np.subtract(x,2))
print(np.negative(x))
print(np.multiply(x, 3))
print(np.divide(x,2))
print(np.floor_divide(x,3))
print(np.power(x,3))
print(np.mod(x,3))

[2 3 4 5]
[-2 -1  0  1]
[ 0 -1 -2 -3]
[0 3 6 9]
[0.  0.5 1.  1.5]
[0 0 0 1]
[ 0  1  8 27]
[0 1 2 0]


In [21]:
# Absolute value
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [22]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [23]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [26]:
# can handle omplex data and return the magnitude
y = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(y)

array([5., 5., 2., 1.])

In [42]:
# Trigonometric functions
theta = np.linspace(0, np.pi, 3)
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))
print("tanh(theta) =", np.tanh(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
tanh(theta) = [0.         0.91715234 0.99627208]


In [46]:
x = np.linspace(-1,1,3)
print("x         =", x)
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x         = [-1.  0.  1.]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [52]:
# Exponents
x = [1, 2, 3]
print("x   =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3,x))

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [53]:
# Logarithms
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [54]:
# Specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [55]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [58]:
# Aggregates
x = np.arange(1,6)
np.add.reduce(x)

15

In [59]:
np.multiply.reduce(x)

120

In [60]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [61]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [63]:
# Outer products
x = np.arange(1,6)
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [65]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [69]:
np.multiply.outer(x-2,x+3)

array([[-4, -5, -6, -7, -8],
       [ 0,  0,  0,  0,  0],
       [ 4,  5,  6,  7,  8],
       [ 8, 10, 12, 14, 16],
       [12, 15, 18, 21, 24]])

In [70]:
# Summing
L = np.random.random(100)
sum(L)

47.51294159911191

In [71]:
np.sum(L)   # faster

47.5129415991119

In [72]:
# Minimum and Maximum
np.min(L), np.max(L)

(0.004695476192547066, 0.9883738380592262)

In [78]:
M = np.random.randint(10,size=(3,4))
print(M)
print(M.sum())
print(M.sum(axis=0))  # sum by column
print(M.sum(axis=1))  # sum by row
print(M.max(axis=0))  # max by column
print(M.max(axis=1))  # max by row

[[5 7 0 8]
 [4 6 5 8]
 [2 3 9 7]]
64
[11 16 14 23]
[20 23 21]
[5 7 9 8]
[8 8 9]
[1.24721913 1.69967317 3.68178701 0.47140452]


In [102]:
N = np.random.randint(10,size=6)
print(N)
print(np.std(N))
print(np.var(N))
print(np.mean(N))
print(np.median(N))
print(np.sum(N))
print(np.prod(N))
print(np.max(N))
print(np.argmax(N))
print(np.percentile(N,75))
# np.median(N) = np.percentile(N, 50)

[3 5 9 4 4 6]
1.9507833184532706
3.805555555555555
5.166666666666667
4.5
31
12960
9
2
5.75
