In [1]:
import numpy as np

In [4]:
"""="""
a = np.arange(4)
b = a
c = a
d = b
a[0] = 11
print(a)
print(b)
print(c)
print("b is a:", b is a)
print("c is a:", c is a)
print("d is b:", d is b)

d[1:3] = [22, 33]
print(a)
print(b)
print(c)

[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
b is a: True
c is a: True
d is b: True
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


In [5]:
"""copy"""
print(a)
b = a.copy()
print(b)
a[3] = 44
print(a)
print(b)

[11 22 33  3]
[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
