In [1]:
import numpy as np

In [2]:
# list to array
array = np.array([
    [1, 3, 5],
    [2, 4, 6]
])
array

array([[1, 3, 5],
       [2, 4, 6]])

In [3]:
# dimension
print('number of dimension:', array.ndim)

number of dimension: 2


In [4]:
# number of rows, number of columns
array.shape

(2, 3)

In [21]:
# number of eleents = nrows * ncols
array.size
np.prod(array.shape) # product of (2, 3)

6

In [6]:
# 1d array
a = np.array([2, 23, 4], dtype=np.float)
print(a.dtype)
a

array([ 2., 23.,  4.])

In [24]:
# change data type
a.astype(np.str)

array(['1.0', '1.4736842105263157', '1.9473684210526314',
       '2.4210526315789473', '2.894736842105263', '3.3684210526315788',
       '3.8421052631578947', '4.315789473684211', '4.789473684210526',
       '5.263157894736842', '5.7368421052631575', '6.2105263157894735',
       '6.684210526315789', '7.157894736842105', '7.63157894736842',
       '8.105263157894736', '8.578947368421051', '9.052631578947368',
       '9.526315789473683', '10.0'], dtype='<U32')

In [7]:
# multi dimensional array
a = np.array([[2, 3, 4],
              [3, 4, 5]])
a

array([[2, 3, 4],
       [3, 4, 5]])

In [8]:
# all 0s array
a  = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# all 1s array
a = np.ones((3, 4), dtype=np.int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
# all empty array
a = np.empty((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# arange(start, end, step)
a = np.arange(10, 21, 2)
a

array([10, 12, 14, 16, 18, 20])

In [13]:
# np.linspace(start, end, num_elements)
a = np.linspace(1, 10, 20)
print(a[0], a[-1], a.size)
a

1.0 10.0 20


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [14]:
# reshape()
b = a.reshape((5, 4))
b

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [18]:
c = np.reshape(a, (10, 2))
c

array([[ 1.        ,  1.47368421],
       [ 1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105],
       [ 3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474],
       [ 7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158],
       [ 9.52631579, 10.        ]])