In [1]:
import numpy as np

In [2]:
# list to array
array = np.array([
    [1, 3, 5],
    [2, 4, 6]
])
array

array([[1, 3, 5],
       [2, 4, 6]])

In [3]:
# dimension
print('number of dimension:', array.ndim)

number of dimension: 2


In [4]:
# number of rows, number of columns
array.shape

(2, 3)

In [5]:
# number of eleents = nrows * ncols
array.size

6

In [6]:
"""create np arrays"""
# 1d array
a = np.array([2, 23, 4], dtype=np.float)
a

array([ 2., 23.,  4.])

In [7]:
# multi dimensional array
a = np.array([[2, 3, 4],
              [3, 4, 5]])
a

array([[2, 3, 4],
       [3, 4, 5]])

In [8]:
# all 0s array
a  = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# all 1s array
a = np.ones((3, 4), dtype=np.int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
# all empty array
a = np.empty((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# arange(start, end, step)
a = np.arange(10, 21, 2)
a

array([10, 12, 14, 16, 18, 20])