In [1]:
# 1
import numpy as np 

In [3]:
# 2 show np version and configuration
print(np.__version__)
np.show_config()

1.16.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [4]:
# 3 create a zero vector with length of 10
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 4 how to find the memory size of an array
z = np.zeros((10, 10))
z.size * z.itemsize

800

In [7]:
# 5 get the document of fumction add
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
# 6 create a zero vector with length of 10, except the 5th value as 1
z = np.zeros((10))
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
# 7 creata a vector with range from 10 to 49
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
# 8 flip a vector (the last element becomes the 1st one)
z = np.arange(10)
z[::-1]
np.flip(z)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
# 9 create a 3x3 array with value from 0 to 8
z = np.arange(9).reshape(3, 3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# 10 find the position of non-zero element in [1, 2, 0, 0, 4, 0]
z = [1, 2, 0, 0, 4, 0]
np.nonzero(z)

(array([0, 1, 4], dtype=int64),)

In [18]:
# 11 create a 3x3 identity matrix (1 on diagnol and 0 for the rest)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# 12 create a 3x3x3 random array
np.random.random((3, 3, 3))

array([[[0.98849597, 0.20708515, 0.60975416],
        [0.45711488, 0.9614041 , 0.60511282],
        [0.85361762, 0.00526133, 0.34096951]],

       [[0.66741371, 0.44661174, 0.16088234],
        [0.35497886, 0.06836824, 0.93615214],
        [0.06104942, 0.57460413, 0.96503408]],

       [[0.97567423, 0.81115981, 0.628614  ],
        [0.15910824, 0.0802131 , 0.70853758],
        [0.36085426, 0.08204847, 0.37600919]]])

In [23]:
# 13 create a 10x10 random array and find its maximum and minimum
z = np.random.random((10, 10))
print(z)
print(z.max())
print(z.min())

[[5.60305975e-01 2.32769570e-01 9.05198186e-02 1.91105901e-01
  8.70262933e-01 7.64611819e-01 1.36671605e-01 6.36836792e-01
  8.37798532e-01 8.85856978e-01]
 [3.49950381e-01 4.42303606e-01 9.05299031e-01 7.56276862e-01
  4.49021079e-02 4.31732662e-01 6.95954421e-01 4.54654482e-05
  1.25066413e-01 4.63653485e-01]
 [4.21532891e-01 2.79682302e-01 5.78911440e-01 9.68235648e-01
  5.68233091e-01 9.20193161e-01 2.33074912e-01 8.89215924e-01
  4.96775568e-01 8.25863066e-01]
 [2.86571769e-01 8.97337748e-01 2.64970553e-01 7.00346901e-01
  9.24359312e-01 9.27507233e-01 7.26886471e-01 2.41130959e-01
  3.09233679e-01 6.94295058e-01]
 [4.29420944e-01 2.59236988e-02 9.85764547e-01 8.09275928e-01
  3.41841507e-02 7.32899958e-01 4.52824344e-01 5.06412457e-02
  8.08379921e-01 8.07184415e-02]
 [4.47188245e-01 8.14963291e-01 2.03118307e-01 5.92195924e-01
  4.33905381e-01 7.99621529e-01 9.74081160e-01 7.49716284e-01
  5.63992835e-01 3.21557029e-01]
 [9.86020026e-01 7.13471045e-01 4.15413766e-01 2.41680801e

In [25]:
# 14 create a random vector with length of 30 and find its average
z = np.random.random(30)
print(z)
print(z.mean())

[0.54195232 0.23653665 0.64723308 0.23079299 0.14392256 0.22008671
 0.47363595 0.74663898 0.5812239  0.85397633 0.10377823 0.42810189
 0.35936572 0.7533233  0.05390604 0.31539939 0.56007544 0.80565943
 0.26902759 0.56610388 0.13817867 0.65323144 0.55451389 0.47796782
 0.04113609 0.52246947 0.99026387 0.75162911 0.7805537  0.40243915]
0.47343745243198676


In [27]:
# 15 create a 2d array, with bounds of 1 and the rest all as 0
z  = np.ones((6, 5))
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
# 16 for a existing array, add bounds with all 0
z = np.arange(30).reshape(6, 5)
nz = np.zeros([l+2 for l in z.shape])
nz[1:-1, 1:-1] = z
nz

# np.pad(z, pad_width=1, mode='constant', constant_values=0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  4.,  0.],
       [ 0.,  5.,  6.,  7.,  8.,  9.,  0.],
       [ 0., 10., 11., 12., 13., 14.,  0.],
       [ 0., 15., 16., 17., 18., 19.,  0.],
       [ 0., 20., 21., 22., 23., 24.,  0.],
       [ 0., 25., 26., 27., 28., 29.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [67]:
# 17 what are the results of the following expressions?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(False == False)
""" errors occur when converting between data types"""
print(0.3 == 3 * 0.1)
print(0.3 - (3*0.1)) 
print(0.2 * 0.3 == 0.4 * 0.15)
print(0.2*0.3 - (0.4*0.15)) 

nan
False
False
nan
True
False
-5.551115123125783e-17
True
0.0


In [68]:
# 18 create a 5x5 matrix, set 1, 2, 3, 4 under its diagonal
np.diag(1+np.arange(4), k=-1)

z = np.zeros((5, 5))
for i in range(4):
    z[i+1, i] = i+1
z

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [72]:
# 19 creata a 8x8 matrix, and set it like a chessboard
z = np.zeros((8, 8))
z[0::2, 0::2] = 1
z[1::2, 1::2] = 1 
z

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [73]:
# 20 considering a array of shape(6, 7, 8), what's the index (x, y, z) of the 100th element?
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [75]:
# 21 create a chessboard-like matrix of 8x8 with np.tile()
tile = np.array([[1, 0],
                 [0, 1]])
np.tile(tile, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [77]:
# 22 normalize a 5x5 random matrix
z = np.random.random((5, 5))
(z-z.min())/(z.max()-z.min())

array([[0.47075706, 0.68902499, 0.99298051, 0.88263209, 0.79830005],
       [0.13989227, 0.22577004, 0.66425793, 0.2509405 , 0.13765555],
       [0.79651489, 0.43489204, 0.09223384, 0.37403949, 0.13833269],
       [0.85820833, 0.23580064, 0.36263511, 0.26197793, 0.55241579],
       [1.        , 0.23107605, 0.187103  , 0.        , 0.38872053]])

In [78]:
# 23 create a custom dtype that describes color as (RGBA)
color = np.dtype([("r", np.ubyte,1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [80]:
# 24 what's the shape of the product if you multiply a 5x3 matrix by a 3x2 matrix
np.dot(np.random.random((5, 3)), np.random.random((3, 2)))

array([[0.6357857 , 0.37335443],
       [1.15235625, 0.85726829],
       [0.39564502, 0.56771574],
       [1.06407406, 0.74174633],
       [0.81461518, 0.74278793]])

In [83]:
# 25 given an array, change the sign for values between 3 and 8
z = np.arange(12)
z[(z>3) & (z<=8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11])