In [1]:
import numpy as np

In [5]:
"""bincount"""
x = np.array([1, 2, 3, 4, 0, 1, 4])
np.bincount(x)

array([1, 2, 1, 1, 2], dtype=int64)

In [6]:
w = np.array([0.3, 0.5, 0.7, 0.6, 0.1, -0.9, 1])
np.bincount(x, weights=w)

array([ 0.1, -0.6,  0.5,  0.7,  1.6])

In [11]:
# minlength > num of bins, set to 0
np.bincount(x, minlength=7)

array([1, 2, 1, 1, 2, 0, 0], dtype=int64)

In [17]:
"""around, floor, ceil"""
np.around([-0.245, -0.126, 1.3527, 2.1235, 9.0267])

array([-0., -0.,  1.,  2.,  9.])

In [19]:
np.around([-0.245, -0.126, 1.3527, 2.1235, 9.0267], decimals=2)

array([-0.24, -0.13,  1.35,  2.12,  9.03])

In [20]:
np.around([3, 5, 17, 265], decimals=-1)

array([  0,   0,  20, 260])

In [21]:
np.around([3, 5, 17, 265], decimals=-2)

array([  0,   0,   0, 300])

In [22]:
np.floor([-0.1, -1.7, 1.4, 1.6 ])

array([-1., -2.,  1.,  1.])

In [23]:
np.ceil([-0.1, -1.7, 1.4, 1.6 ])

array([-0., -1.,  2.,  2.])

In [26]:
"""where"""
# where(condition, return this if True, return this if False)
# find and replace the rest
a = np.array([[1, 0],
              [2, -2],
              [-3, 1]])
np.where(a > 0, a, 0)

array([[1, 0],
       [2, 0],
       [0, 1]])

In [27]:
np.where(a > 0, a, 'non-positive')

array([['1', 'non-positive'],
       ['2', 'non-positive'],
       ['non-positive', '1']], dtype='<U12')

In [49]:
a = np.array([1, 5, 7])
b = np.array([2, 6, 8])
con = np.array([True, False, True])
np.where(con, a, b)

array([1, 6, 7])

In [31]:
"""general"""
a = np.array([4, 9, 16])
# square root
np.sqrt(a)

array([2., 3., 4.])

In [34]:
# square
np.square(a)

array([ 16,  81, 256], dtype=int32)

In [32]:
# absolute value
np.abs(a)

array([ 4,  9, 16])

In [39]:
# add
b = np.array([3, 10, 7])
np.add(a, b)

array([ 7, 19, 23])

In [40]:
# multiply
np.multiply(a, b)

array([ 12,  90, 112])

In [41]:
# compare
np.greater(a, b)

array([ True, False,  True])

In [42]:
"""check element"""
a = np.array([[1, -2, -7],
              [-3, 6, 2],
              [-4, 3, 2]])
np.any(a > 0)

True

In [43]:
np.all(a > 0)

False

In [46]:
"""unique"""
a = np.array([12, 11, 34, 23, 12, 8, 11])
np.unique(a)

array([ 8, 11, 12, 23, 34])

In [47]:
"""check if element is in a list"""
np.in1d(a, [11, 12, 13])

array([ True,  True, False, False,  True, False,  True])