In [1]:
import numpy as np

In [5]:
a = np.arange(3, 15).reshape((3, 4))
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [6]:
# call a row
a[2]

array([11, 12, 13, 14])

In [21]:
# last 2 rows
a[-2:]

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [24]:
a[1:3, 1:4]

array([[ 8,  9, 10],
       [12, 13, 14]])

In [7]:
a[0][2]

5

In [8]:
a[0, 3]

6

In [9]:
a[1, 1:3]

array([8, 9])

In [10]:
for row in a:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [13]:
# transpose np.T
print(a.T, '\n')
for col in a.T:
    print(col)

[[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]] 

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [16]:
# convert to 1 dimensional array
a.flatten()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])