In [1]:
import numpy as np

In [3]:
# flatten()
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = a.flatten()
print(a.shape)
print(b.shape)
b

(2, 3)
(6,)


array([1, 2, 3, 4, 5, 6])

In [8]:
# flip()
a = np.arange(12).reshape(3, 4)
np.flip(a)

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [14]:
# flip rows
a = np.arange(12).reshape(3, 4)
print(a)
a[::-1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [20]:
"""reshape vs resize"""
# reshape() returns a new array, no change on original array
# resize() returns nothing, but changes the original array
a = np.arange(12)
b = a.reshape(3, 4)
print("a:", a)
print("b:", b)
c = a.resize(4, 3)
print("a:", a)
print("c:", c)

a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
b: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
c: None


In [37]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
100


In [34]:
# ravel()  is a library level function
# modifying value would change the original array
d = a.ravel()
d[-1] = 100
print(d)
print(a)

[  0   1   2   3   4   5   6   7   8   9  10 100]
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10 100]]


In [33]:
# flatten() is a method of ndarray object
# modifying the value does not effect original array
e  =a.flatten()
e[-1] = 50
print(e)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 50]
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10 100]]
