In [1]:
import numpy as np

In [4]:
"""stack"""
a = np.arange(3)
b = np.arange(3, 6)
print(a, b)

[0 1 2] [3 4 5]


In [7]:
# vertical stack
np.vstack((a, b))

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
# hotizontal stack
np.hstack((a, b))

array([0, 1, 2, 3, 4, 5])

In [22]:
# array to matrix
print(a.shape)
print(a[np.newaxis, :].shape)
a[np.newaxis, :]

(3,)
(1, 3)


array([[0, 1, 2]])

In [18]:
c = a[:, np.newaxis]
print(c.shape)
c

(3, 1)


array([[0],
       [1],
       [2]])

In [21]:
"""concatenate"""
np.concatenate((a, b, b, a), axis=0)

array([0, 1, 2, 3, 4, 5, 3, 4, 5, 0, 1, 2])

In [24]:
d = a[np.newaxis, :]
e = b[np.newaxis, :]
np.concatenate((d, e, d, e), axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [25]:
np.concatenate((d, e, e, d), axis=1)

array([[0, 1, 2, 3, 4, 5, 3, 4, 5, 0, 1, 2]])

In [31]:
"""split"""
a = np.arange(12).reshape(3, 4)
print(np.split(a, 2, axis=1))
print(np.split(a, 2, axis=1)[0])
print(np.split(a, 2, axis=1)[1])

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [32]:
np.split(a, 3, axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [35]:
np.vsplit(a, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [36]:
np.hsplit(a, 4)

[array([[0],
        [4],
        [8]]), array([[1],
        [5],
        [9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]